# Generated by Django 2.1.1 on 2018-09-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180926_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(default='aidana', max_length=100),
        ),
    ]
